# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for develop

on:
    push:
        branches:
            - 'develop' # 只针对 develop 分支
        paths:
            - '.github/workflows/*'
            # - '__test__/**' # develop 不需要立即测试
            - 'src/**'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'bin/*'

jobs:
    deploy-develop:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "47.104.239.122" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |

                  ssh -i ~/.ssh/id_rsa work@47.104.239.122 "
                    cd /home/work/sudu-logo/koa-editor-server;
                    git remote add origin https://shdulu:shdulu990705@github.com/shdulu/koa-editor-server.git;
                    git checkout develop;
                    git pull origin develop;
                    git remote remove origin;
                    docker-compose build editor-server;
                    docker-compose up -d;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
