# 文档地址 https://docs.github.com/cn/actions/quickstart

name: test

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/**'
            - '__test__/**'
            - 'src/**'

jobs:
    test:
        runs-on: ubuntu-latest # ?? Ubuntu 是基于 Debian 的 Linux 操作系统。
        steps: # 步骤
            - uses: actions/checkout@v2 # git pull， 第三方actions
            - name: Use Node.js
              uses: actions/setup-node@v1 # 安装nodejs
              with:
                  node-version: 14 # 使用版本
            - name: lint an test
              run: | # 安装依赖 代码检查 远程测试
                  npm install
                  npm run lint 
                  npm run test:remote
